-- Enable PostGIS extension for spatial queries (GPS coordinates)
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Custom Enumerations
CREATE TYPE user_role AS ENUM ('joueur', 'gerant', 'admin');
CREATE TYPE surface_type AS ENUM ('gazon', 'gazon_synthetique', 'bitume');
CREATE TYPE reservation_status AS ENUM ('en_attente', 'confirmee', 'annulee');
CREATE TYPE payment_method AS ENUM ('wave', 'orange_money', 'cash');

-- 2. Profiles Table (extends auth.users)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    phone TEXT,
    avatar_url TEXT,
    role user_role NOT NULL DEFAULT 'joueur',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) on Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Terrains Table
CREATE TABLE public.terrains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    description TEXT,
    adresse TEXT NOT NULL,
    quartier TEXT NOT NULL,
    localisation GEOMETRY(Point, 4326) NOT NULL, -- GPS coordinates (SRID 4326)
    prix_heure NUMERIC(10, 2) NOT NULL CHECK (prix_heure >= 0),
    surface surface_type NOT NULL,
    disponible BOOLEAN DEFAULT TRUE NOT NULL,
    gerant_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    images TEXT[] DEFAULT '{}'::TEXT[] NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) on Terrains
ALTER TABLE public.terrains ENABLE ROW LEVEL SECURITY;

-- 4. Reservations Table
CREATE TABLE public.reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terrain_id BIGINT REFERENCES public.terrains(id) ON DELETE CASCADE NOT NULL,
    joueur_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    date_reservation DATE NOT NULL,
    heure_debut TIME NOT NULL,
    heure_fin TIME NOT NULL,
    statut reservation_status DEFAULT 'en_attente' NOT NULL,
    montant NUMERIC(10, 2) NOT NULL CHECK (montant >= 0),
    methode_paiement payment_method NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT chk_time_range CHECK (heure_debut < heure_fin)
);

-- Enable Row Level Security (RLS) on Reservations
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;

-- 5. Avis Table
CREATE TABLE public.avis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    terrain_id BIGINT REFERENCES public.terrains(id) ON DELETE CASCADE NOT NULL,
    joueur_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
    note INTEGER NOT NULL CHECK (note BETWEEN 1 AND 5),
    commentaire TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) on Avis
ALTER TABLE public.avis ENABLE ROW LEVEL SECURITY;

-- 6. Indexes
-- Spatial index on terrains.localisation using GIST (highly optimized for geographic queries)
CREATE INDEX IF NOT EXISTS idx_terrains_localisation ON public.terrains USING GIST (localisation);

-- Search and filter indexes
CREATE INDEX IF NOT EXISTS idx_reservations_terrain_id ON public.reservations (terrain_id);
CREATE INDEX IF NOT EXISTS idx_reservations_joueur_id ON public.reservations (joueur_id);
CREATE INDEX IF NOT EXISTS idx_reservations_date_reservation ON public.reservations (date_reservation);
CREATE INDEX IF NOT EXISTS idx_avis_terrain_id ON public.avis (terrain_id);

-- 7. Trigger Function to automatically create a Profile on Supabase Auth Sign Up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, avatar_url, role)
    VALUES (
        new.id,
        COALESCE(new.raw_user_meta_data->>'full_name', ''),
        COALESCE(new.raw_user_meta_data->>'avatar_url', ''),
        COALESCE((new.raw_user_meta_data->>'role')::user_role, 'joueur'::user_role)
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger to execute the function on auth.users insert
CREATE OR REPLACE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
